services:
    menu_config:
      class: %cu_labs_admin.menu.class%
      factory-service: cu_labs_admin.menu_config_builder
      factory: getMenu
      scope:   request
      arguments:
          - @request
          - %culabs.admin.admin_menu%
      tabs:
          - { name: knp_menu.menu. alias: main }